// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository/userrepo/querier.go
//
// Generated by this command:
//
//	mockgen -source=./repository/userrepo/querier.go -destination=./repository/userrepo/_mock/mock_querier.go
//

// Package mock_userrepo is a generated GoMock package.
package mock_userrepo

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	userrepo "github.com/Yuki-TU/oapi-codegen-sample/repository/userrepo"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CreateUsers mocks base method.
func (m *MockQuerier) CreateUsers(ctx context.Context, db userrepo.DBTX, arg userrepo.CreateUsersParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUsers", ctx, db, arg)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUsers indicates an expected call of CreateUsers.
func (mr *MockQuerierMockRecorder) CreateUsers(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUsers", reflect.TypeOf((*MockQuerier)(nil).CreateUsers), ctx, db, arg)
}

// GetByUserID mocks base method.
func (m *MockQuerier) GetByUserID(ctx context.Context, db userrepo.DBTX, id int64) (userrepo.GetByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, db, id)
	ret0, _ := ret[0].(userrepo.GetByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockQuerierMockRecorder) GetByUserID(ctx, db, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockQuerier)(nil).GetByUserID), ctx, db, id)
}

// UpdateUser mocks base method.
func (m *MockQuerier) UpdateUser(ctx context.Context, db userrepo.DBTX, arg userrepo.UpdateUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, db, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockQuerierMockRecorder) UpdateUser(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockQuerier)(nil).UpdateUser), ctx, db, arg)
}

// UpdateUserMail mocks base method.
func (m *MockQuerier) UpdateUserMail(ctx context.Context, db userrepo.DBTX, arg userrepo.UpdateUserMailParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserMail", ctx, db, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserMail indicates an expected call of UpdateUserMail.
func (mr *MockQuerierMockRecorder) UpdateUserMail(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserMail", reflect.TypeOf((*MockQuerier)(nil).UpdateUserMail), ctx, db, arg)
}
