// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository/userrepo/wrapper.go
//
// Generated by this command:
//
//	mockgen -source=./repository/userrepo/wrapper.go -destination=./repository/userrepo/_mock/mock_userrepo.go
//

// Package mock_userrepo is a generated GoMock package.
package mock_userrepo

import (
	context "context"
	reflect "reflect"

	userrepo "github.com/Yuki-TU/oapi-codegen-sample/repository/userrepo"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepoer is a mock of UserRepoer interface.
type MockUserRepoer struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoerMockRecorder
}

// MockUserRepoerMockRecorder is the mock recorder for MockUserRepoer.
type MockUserRepoerMockRecorder struct {
	mock *MockUserRepoer
}

// NewMockUserRepoer creates a new mock instance.
func NewMockUserRepoer(ctrl *gomock.Controller) *MockUserRepoer {
	mock := &MockUserRepoer{ctrl: ctrl}
	mock.recorder = &MockUserRepoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepoer) EXPECT() *MockUserRepoerMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockUserRepoer) GetByUserID(ctx context.Context, db userrepo.DBTX, id int64) (userrepo.GetByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, db, id)
	ret0, _ := ret[0].(userrepo.GetByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockUserRepoerMockRecorder) GetByUserID(ctx, db, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockUserRepoer)(nil).GetByUserID), ctx, db, id)
}

// UpdateUser mocks base method.
func (m *MockUserRepoer) UpdateUser(ctx context.Context, db userrepo.DBTX, arg userrepo.UpdateUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, db, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserRepoerMockRecorder) UpdateUser(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserRepoer)(nil).UpdateUser), ctx, db, arg)
}

// UpdateUserMail mocks base method.
func (m *MockUserRepoer) UpdateUserMail(ctx context.Context, db userrepo.DBTX, arg userrepo.UpdateUserMailParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserMail", ctx, db, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserMail indicates an expected call of UpdateUserMail.
func (mr *MockUserRepoerMockRecorder) UpdateUserMail(ctx, db, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserMail", reflect.TypeOf((*MockUserRepoer)(nil).UpdateUserMail), ctx, db, arg)
}
