// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetByUserID(ctx context.Context, id int64) (GetByUserIDRow, error)
}

var _ Querier = (*Queries)(nil)
