services:
  app:
    container_name: oapi-app
    build:
      args:
        - target=dev
    volumes:
      - ./:/app
    environment:
      CONTAINER_ENV: true
      GO_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: point_app
      DB_TEST_NAME: point_app_test
      REDIS_HOST: point-app-redis
      REDIS_PORT: 6379
      AWS_ENDPOINT: http://aws:4566
      AWS_ACCESS_KEY_ID: accesskey
      AWS_SECRET_KEY: secretkey
      AWS_REGION: ap-northeast-1
      SENDER_MAIL_ADDRESS: example@example.com
      FRONT_ENDPOINT: http://localhost:3000
    tty: true
    ports:
      - 8081:80
    command: air
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.31
    platform: linux/amd64
    container_name: oapi-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: point_app
      DB_TEST_NAME: point_app_test
    volumes:
      - app-db-data:/var/lib/mysql
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
      - $PWD/_tools/mysql/create_test_db.sh:/docker-entrypoint-initdb.d/create_test_db.sh
    ports:
      - "33306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
volumes:
  app-db-data:
