version: "2"
sql:
  - schema: "../migrations"
    queries: "../../repository/userrepo"
    engine: "mysql"
    gen:
      go:
        package: "userrepo"
        emit_exact_table_names: true
        emit_interface: true
        sql_package: "database/sql"
        out: "../../repository/userrepo"
        emit_methods_with_db_argument: true
        emit_db_tags: true
  - schema: "../migrations"
    queries: "../../repository/transactionrepo"
    engine: "mysql"
    gen:
      go:
        package: "transactionrepo"
        emit_exact_table_names: true
        emit_interface: true
        sql_package: "database/sql"
        out: "../../repository/transactionrepo"
        emit_methods_with_db_argument: true
        emit_db_tags: true
