version: "2"
sql:
  - schema: "../migrations"
    queries: "../../repository/queries"
    engine: "mysql"
    gen:
      go:
        package: "repository"
        emit_exact_table_names: true
        emit_interface: true
        sql_package: "database/sql"
        out: "../../repository"
        emit_methods_with_db_argument: true
        emit_db_tags: true
