// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package userrepo

import (
	"time"
)

// 取引
type Transactions struct {
	// 取引の識別子
	ID uint64 `db:"id"`
	// 送信ユーザのID
	SendingUserID uint64 `db:"sending_user_id"`
	// 受信ユーザのID
	ReceivingUserID uint64 `db:"receiving_user_id"`
	// 取引ポイント
	TransactionPoint int32 `db:"transaction_point"`
	// 取引日時
	TransactionAt time.Time `db:"transaction_at"`
}

// ユーザー
type Users struct {
	// ユーザーの識別子
	ID int64 `db:"id"`
	// 苗字
	FamilyName string `db:"family_name"`
	// 苗字カナ
	FamilyNameKana string `db:"family_name_kana"`
	// 名前
	FirstName string `db:"first_name"`
	// 名前カナ
	FirstNameKana string `db:"first_name_kana"`
	// メールアドレス
	Email string `db:"email"`
	// パスワードハッシュ
	Password string `db:"password"`
	// 送信可能ポイント
	SendingPoint int32 `db:"sending_point"`
	// レコード作成日時
	CreatedAt time.Time `db:"created_at"`
	// レコード修正日時
	UpdateAt time.Time `db:"update_at"`
}
