// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package userrepo

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUsers(ctx context.Context, arg CreateUsersParams) (sql.Result, error)
	GetByUserID(ctx context.Context, id int64) (GetByUserIDRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserMail(ctx context.Context, arg UpdateUserMailParams) error
}

var _ Querier = (*Queries)(nil)
