// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package transactionrepo

import (
	"context"
)

type Querier interface {
	GetByUserID(ctx context.Context, receivingUserID uint64) (Transactions, error)
}

var _ Querier = (*Queries)(nil)
