// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: transactions.sql

package repository

import (
	"context"
)

const getPointByUserID = `-- name: GetPointByUserID :one
SELECT
  ` + "`" + `id` + "`" + `,
  ` + "`" + `sending_user_id` + "`" + `,
  ` + "`" + `receiving_user_id` + "`" + `,
  ` + "`" + `transaction_point` + "`" + `,
  ` + "`" + `transaction_at` + "`" + `
FROM
  ` + "`" + `transactions` + "`" + `
WHERE ` + "`" + `receiving_user_id` + "`" + ` = ?
`

func (q *Queries) GetPointByUserID(ctx context.Context, db DBTX, receivingUserID uint64) (Transactions, error) {
	row := db.QueryRowContext(ctx, getPointByUserID, receivingUserID)
	var i Transactions
	err := row.Scan(
		&i.ID,
		&i.SendingUserID,
		&i.ReceivingUserID,
		&i.TransactionPoint,
		&i.TransactionAt,
	)
	return i, err
}
