production:
  dialect: mysql
  datasource: root@/dbname?parseTime=true
  dir: migrations/mysql
  table: migrations
development:
  dialect: mysql
  datasource:  admin:password@tcp(db:3306)/point_app?parseTime=true
  dir: _tools/migrations
  table: migrations
